       SELECT COBCAP
           ASSIGN       TO  COBCAP-COB
           ORGANIZATION IS LINE SEQUENTIAL
           ACCESS MODE  IS SEQUENTIAL
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
