       SELECT LISTE
           ASSIGN       TO  ASSIGN-LISTE
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-LST
           ALTERNATE RECORD KEY IS CLE2-LST
           WITH DUPLICATES .
