       SELECT MXART3
           ASSIGN       TO  MXART-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MART3
           ALTERNATE RECORD KEY IS CLE2-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE6-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE7-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE8-MART3
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE9-MART3
           WITH DUPLICATES .
