       SELECT MXART2
           ASSIGN       TO  MXART-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MART2
           ALTERNATE RECORD KEY IS CLE2-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE6-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE7-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE8-MART2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE9-MART2
           WITH DUPLICATES .
