       SELECT MXARTSA2
           ASSIGN       TO  MXARTSA-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MASA2
           ALTERNATE RECORD KEY IS CLE2-MASA2 = AGE-MASA2, CAS-MASA2, 
           COD-MASA2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MASA2
           WITH DUPLICATES .
