       SELECT MXARTSA
           ASSIGN       TO  MXARTSA-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MASA
           ALTERNATE RECORD KEY IS CLE2-MASA = AGE-MASA, CAS-MASA, 
           COD-MASA
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MASA
           WITH DUPLICATES .
