       SELECT MXBDIS
           ASSIGN       TO  MXBDIS-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MBDI
           ALTERNATE RECORD KEY IS CLE2-MBDI = AGE-MBDI, CLI-MBDI, 
           TFA-MBDI, CHC-MBDI
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MBDI = AGE-MBDI, DAT-MBDI
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MBDI = CLI-MBDI
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MBDI = TRA-MBDI, AGE-MBDI, 
           DAT-MBDI
           WITH DUPLICATES .
