       SELECT MXBDIS2
           ASSIGN       TO  MXBDIS-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MBDI2
           ALTERNATE RECORD KEY IS CLE2-MBDI2 = AGE-MBDI2, CLI-MBDI2, 
           TFA-MBDI2, CHC-MBDI2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MBDI2 = AGE-MBDI2, DAT-MBDI2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MBDI2 = CLI-MBDI2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MBDI2 = TRA-MBDI2, AGE-MBDI2, 
           DAT-MBDI2
           WITH DUPLICATES .
