      *Fichier Documentation Etendue
       SELECT MXDOCTECEXT2
           ASSIGN       TO  MXDOCTECEXT-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MDTEX2
           ALTERNATE RECORD KEY IS CLE2-MDTEX2 = ORI-MDTEX2, CLE-MDTEX2
           WITH DUPLICATES .
