      *Fichier Documentation Etendue
       SELECT MXDOCTECEXT
           ASSIGN       TO  MXDOCTECEXT-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MDTEX
           ALTERNATE RECORD KEY IS CLE2-MDTEX = ORI-MDTEX, CLE-MDTEX
           WITH DUPLICATES .
