       SELECT MXDOCTEC2
           ASSIGN       TO  MXDOCTEC-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MDTE2
           ALTERNATE RECORD KEY IS CLE2-MDTE2 = ORI-MDTE2, CLE-MDTE2, 
           RAN-MDTE2
           WITH DUPLICATES .
