       SELECT MXDOCTEC
           ASSIGN       TO  MXDOCTEC-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MDTE
           ALTERNATE RECORD KEY IS CLE2-MDTE = ORI-MDTE, CLE-MDTE, 
           RAN-MDTE
           WITH DUPLICATES .
