       SELECT MXFOU
           ASSIGN       TO  MXFOU-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MFOU
           ALTERNATE RECORD KEY IS CLE2-MFOU
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MFOU
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MFOU
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MFOU
           WITH DUPLICATES .
