       SELECT MXHISVTE2
           ASSIGN       TO  MXHISVTE-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MHIV2
           ALTERNATE RECORD KEY IS CLE2-MHIV2 = CLI-MHIV2, CDV-MHIV2, 
           DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MHIV2 = ART-MHIV2, DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MHIV2 = REP-MHIV2, DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MHIV2 = PCI-MHIV2, DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE6-MHIV2 = MAT-MHIV2, DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE7-MHIV2 = DSP-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE8-MHIV2 = DAT-MHIV2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE9-MHIV2
           WITH DUPLICATES .
