       SELECT MXHISVTE
           ASSIGN       TO  MXHISVTE-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MHIV
           ALTERNATE RECORD KEY IS CLE2-MHIV = CLI-MHIV, CDV-MHIV, 
           DSP-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MHIV = ART-MHIV, DSP-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MHIV = REP-MHIV, DSP-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE5-MHIV = PCI-MHIV, DSP-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE6-MHIV = MAT-MHIV, DSP-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE7-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE8-MHIV
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE9-MHIV
           WITH DUPLICATES .
