       SELECT MXLDIS
           ASSIGN       TO  MXLDIS-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MLDI
           ALTERNATE RECORD KEY IS CLE2-MLDI = AGE-MLDI, BON-MLDI, 
           CAS-MLDI
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MLDI = INP-MLDI, ART-MLDI
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MLDI = AGE-MLDI, BON-MLDI, 
           RAN-MLDI
           WITH DUPLICATES .
