       SELECT MXLDIS2
           ASSIGN       TO  MXLDIS-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MLDI2
           ALTERNATE RECORD KEY IS CLE2-MLDI2 = AGE-MLDI2, BON-MLDI2, 
           CAS-MLDI2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MLDI2 = INP-MLDI2, ART-MLDI2
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE4-MLDI2 = AGE-MLDI2, BON-MLDI2, 
           RAN-MLDI2
           WITH DUPLICATES .
