       SELECT MXMARQUE
           ASSIGN       TO  MXMARQUE-COB
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS
           RECORD KEY   IS CLE1-MMAR
           ALTERNATE RECORD KEY IS CLE2-MMAR
           WITH DUPLICATES 
           ALTERNATE RECORD KEY IS CLE3-MMAR
           WITH DUPLICATES .
