       SELECT MXPARDIS
           ASSIGN       TO  MXPARDIS-COB
           ORGANIZATION IS RELATIVE
           ACCESS MODE  IS RANDOM
           RELATIVE KEY IS W-MXPARDIS
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
