       SELECT MXPARAM
           ASSIGN       TO  MXPARAM-COB
           ORGANIZATION IS RELATIVE
           ACCESS MODE  IS RANDOM
           RELATIVE KEY IS W-MXPARAM
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
