       SELECT RECH
           ASSIGN       TO  ASSIGN-RECH
           ORGANIZATION IS LINE SEQUENTIAL
           ACCESS MODE  IS SEQUENTIAL
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
