       SELECT RECHCMD
           ASSIGN       TO  ASSIGN-RECHCMD
           ORGANIZATION IS BINARY SEQUENTIAL
           ACCESS MODE  IS SEQUENTIAL
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
