       SELECT OPTIONAL TEST-REL
           ASSIGN       TO  TEST-REL-COB
           ORGANIZATION IS RELATIVE
           ACCESS MODE  IS DYNAMIC
           RELATIVE KEY IS KEY-TR
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
