       SELECT OPTIONAL TEST-SEQ2
           ASSIGN       TO  TEST-SEQ2-COB
           ORGANIZATION IS LINE SEQUENTIAL
           ACCESS MODE  IS SEQUENTIAL
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
