       SELECT OPTIONAL TEST-SEQ
           ASSIGN       TO  TEST-SEQ-COB
           ORGANIZATION IS LINE SEQUENTIAL
           ACCESS MODE  IS SEQUENTIAL
           LOCK MODE    IS MANUAL
           FILE STATUS  IS FILE-STATUS.
