<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
   <xsl:output method="text" encoding="iso-8859-1" />
<xsl:template match="/mistral"><xsl:value-of select="enteteliste/zontitcod"/>;<xsl:value-of select="enteteliste/zontitnom"/>;<xsl:value-of select="enteteliste/zontitcol01"/>;<xsl:value-of select="enteteliste/zontitcol02"/>;<xsl:value-of select="enteteliste/zontitcol03"/>;<xsl:value-of select="enteteliste/zontitcol04"/>;<xsl:value-of select="enteteliste/zontitcol05"/>;<xsl:value-of select="enteteliste/zontitcol06"/>;<xsl:value-of select="enteteliste/zontitcol07"/>;<xsl:value-of select="enteteliste/zontitcol08"/>;<xsl:value-of select="enteteliste/zontitcol09"/>;<xsl:value-of select="enteteliste/zontitcol10"/>;<xsl:value-of select="enteteliste/zontitcol11"/>;<xsl:value-of select="enteteliste/zontitcol12"/>;<xsl:value-of select="enteteliste/zontitcol13"/>;<xsl:value-of select="enteteliste/zontitcol14"/>;<xsl:value-of select="enteteliste/zontitcol15"/>;<xsl:value-of select="enteteliste/zontitcol16"/>;<xsl:value-of select="enteteliste/zontitcol17"/>;<xsl:value-of select="enteteliste/zontitcol18"/>;<xsl:value-of select="enteteliste/zontitcol19"/>;<xsl:value-of select="enteteliste/zontitcol20"/>;
<xsl:apply-templates select="lig" />
</xsl:template>
<xsl:template match="lig"><xsl:value-of select="ide"/>;<xsl:value-of select="nom"/>;<xsl:value-of select="col01"/>;<xsl:value-of select="col02"/>;<xsl:value-of select="col03"/>;<xsl:value-of select="col04"/>;<xsl:value-of select="col05"/>;<xsl:value-of select="col06"/>;<xsl:value-of select="col07"/>;<xsl:value-of select="col08"/>;<xsl:value-of select="col09"/>;<xsl:value-of select="col10"/>;<xsl:value-of select="col11"/>;<xsl:value-of select="col12"/>;<xsl:value-of select="col13"/>;<xsl:value-of select="col14"/>;<xsl:value-of select="col15"/>;<xsl:value-of select="col16"/>;<xsl:value-of select="col17"/>;<xsl:value-of select="col18"/>;<xsl:value-of select="col19"/>;<xsl:value-of select="col20"/>;
</xsl:template>
</xsl:stylesheet>      
