cd %USERPROFILE%\Cookies
copy %USERNAME%*192.168.236*.txt  MANIDOCWEB.%USERNAME%
rcp MANIDOCWEB.%USERNAME% SERVEUR_MIS.mistral:/acuf/mx0001/ficem/MANITOU/%USERNAME%/
rsh SERVEUR_MIS -l mistral /acuf/mistral/px/PANIERMANIDOC %USERNAME%
del %USERNAME%*192.168.236*.txt 
del MANIDOCWEB.%USERNAME% 
